---
abstract: 'Install Perl distributions on Slackware Linux'
author:
  - 'Andreas Voegele <andreas@andreasvoegele.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-Dist-Slackware
provides:
  CPANPLUS::Dist::Slackware:
    file: lib/CPANPLUS/Dist/Slackware.pm
    version: 0.03
  CPANPLUS::Dist::Slackware::PackageDescription:
    file: lib/CPANPLUS/Dist/Slackware/PackageDescription.pm
    version: 0.03
requires:
  CPANPLUS: 0
  Cwd: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  IO::Compress::Gzip: 0
  IPC::Cmd: 0
  Locale::Maketext::Simple: 0
  POSIX: 0
  Params::Check: 0
  Pod::Find: 0
  Pod::Simple: 0
  Text::Wrap: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/voegelas/CPANPLUS-Dist-Slackware.git
version: 0.03
