---
abstract: 'Install Perl distributions on Slackware Linux'
author:
  - 'Andreas Voegele <voegelas@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-Dist-Slackware
requires:
  CPANPLUS: 0
  Cwd: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  IO::Compress::Gzip: 0
  IPC::Cmd: 0
  Locale::Maketext::Simple: 0
  Module::CoreList: 0
  Module::Pluggable: 0
  POSIX: 0
  Params::Check: 0
  Pod::Find: 0
  Pod::Simple: 0
  Text::Wrap: 0
  parent: 0
  perl: 5.010
  version: 0.77
resources:
  repository: git://github.com/voegelas/CPANPLUS-Dist-Slackware.git
version: 1.016
